version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/db.json:/app/db.json
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
